apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: add-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: add
    spec:
      containers:
      - name: add
        image: jbienkowski311/add:0.2.0
        imagePullPolicy: Never
        ports:
        - containerPort: 8080