version: '3'

services:
  calculator:
    build: ./calc
    links:
      - addition
      - subtraction
      - multiplication
    ports:
      - "3000:3000"

  addition:
    build: ./add

  subtraction:
    build: ./sub
    links:
      - addition

  multiplication:
    build: ./mul
    links:
      - addition