apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: div-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: div
    spec:
      containers:
      - name: div
        image: jbienkowski311/div:1.0.0
        imagePullPolicy: Never
        ports:
        - containerPort: 5000