apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mul-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mul
    spec:
      containers:
      - name: mul
        image: jbienkowski311/mul:1.0.0
        imagePullPolicy: Never
        env:
        - name: ADD_HOST
          value: add-service
        ports:
        - containerPort: 5000